#!/bin/bash
set -e

#get flahsers directory on the laptop
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source dev-config.sh
DOCKER_IMAGE="sdkmanager-$VERSION.$BUILD_NUM-${BASE_OS}_docker.tar.gz"
ENV_FILE="$DIR"/.env
IMAGE="sdkmanager:$VERSION.$BUILD_NUM-${BASE_OS}"

make_needed_files () {
    
    #delete the old and update the .env file
    if [ -f "$ENV_FILE" ]; then
        rm "$ENV_FILE"
        echo "deleted old .env"
    fi
    
    
    #make the .env file
cat <<EOF > .env
DOCKER_IMAGE=${IMAGE}
CURRENT_DIR=${DIR}
EOF
    
    #make a mount directory for the files that jetson might download
    if [ ! -d "$DIR"/mount ] ; then
        mkdir "$DIR"/mount
        echo 'make the mount directory'
    fi

}

# searches the assets directory for image then loads its, otherwise asks
# prompts user to follow file downloading instructions
try_load_image () {
    #if image does not exist check if it is in the assets folder
    if [ ! -f "$DIR/assets/$DOCKER_IMAGE" ]; then
        echo "the nesscary docker image is not found"
        echo "you need to download it, instructions in README.md"
        echo "once you have downloaded it, place it in : "
        echo "$DIR/assets"
        exit 1
    else
        echo "image tar.gz found, begining loading process"
        echo ""
        docker load -i "$DIR/assets/$DOCKER_IMAGE"
    fi
}

# searches the available docker images for the sdkmanager image
image_search () {
    #check if we already have the image loaded
    images_list=($(docker images --format "{{.Repository}}:{{.Tag}}"))
    found_image="false"
    
    for img in "${images_list[@]}"; do
        if [ "$img" = "sdkmanager:$VERSION.$BUILD_NUM-$BASE_OS" ] ; then
            echo "image found on device"
            found_image="true"
            break
        fi
    done
    
    if [ "$found_image" = "false" ] ; then
        echo "image is not found, searching for $DOCKER_IMAGE file in assets"
        try_load_image
    fi
    
}

gui_mode () {
    make_needed_files
    echo "starting flashing process in gui mode"
    image_search
    echo "run the sdkmanager command in the terminal"
    docker compose -f "$DIR"/moduels/docker-compose.flash.yaml --project-directory "$DIR" up
    echo "running after compose"
    
    #docker run -it --rm \
    #--cap-add=SYS_ADMIN \
    #--security-opt seccomp=unconfined \
    #--env DISPLAY=$DISPLAY \
    #--env QT_X11_NO_MITSHM=1 \
    #--volume /tmp/.X11-unix:/tmp/.X11-unix:rw \
    #--entrypoint /bin/bash \
    #"sdkmanager:$VERSION.$BUILD_NUM-$BASE_OS"
}

clean_up () {
    echo "starting clean up"
    docker rmi -f "sdkmanager:$VERSION.$BUILD_NUM-$BASE_OS"
    rm -r "$DIR"/mount
    rm "$DIR"/.env
    echo "done cleaning up"

}


echo "============================================================================================"
echo " "
cat "$DIR/assets/title.txt"
echo " "
echo "============================================================================================"
echo "option : "
echo " "
echo "1. start the nvidia jetson sdk"
echo " "
echo "2. start the system clean up process"
echo " "
echo "3. quit"
echo " "
read -p "select : " choice
echo " "


if [ "$choice" = '1' ]; then
    gui_mode
    elif [ "$choice" = '2' ]; then
    clean_up
    elif [ "$choice" = '3' ]; then
    echo "thank you for giving this a shot"
    exit 0
else
    echo "invalid choice restart script"
fi
